name = "leangineering"
version = "0.1.0"
defaultTargets = ["leangineering"]

[[require]]
name = "html"
git = "https://github.com/paulbutcher/lean-html"
rev = "v0.9.0"

[[require]]
name = "routing"
git = "https://github.com/paulbutcher/lean-routing.git"
rev = "v0.7.2"

[[require]]
name = "markdown"
git = "https://github.com/paulbutcher/lean-markdown"
rev = "v0.7.1"

[[require]]
name = "datastar"
git = "https://github.com/carlohamalainen/datastar-lean"
rev = "055f9f275776f89f4e728fe72f54570c36cfeec0"

[[lean_lib]]
name = "Leangineering"

[[lean_exe]]
name = "leangineering"
root = "Main"
